# Generated by Django for Combiner models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва марки')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('logo', models.URLField(blank=True, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='CombinerCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excellent', 'Відмінний стан'), ('good', 'Хороший стан'), ('normal', 'Задовільний'), ('poor', 'Потребує ремонту')], max_length=50, unique=True, verbose_name='Стан')),
            ],
            options={
                'verbose_name': 'Стан комбайна',
                'verbose_name_plural': 'Стани комбайнів',
            },
        ),
        migrations.CreateModel(
            name='CombinerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип комбайна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип комбайна',
                'verbose_name_plural': 'Типи комбайнів',
            },
        ),
        migrations.CreateModel(
            name='Combiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель комбайна')),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('working_hours', models.PositiveIntegerField(verbose_name='Годин роботи')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Дизель'), ('gasoline', 'Бензин'), ('gas', 'Газ')], max_length=20, verbose_name='Тип палива')),
                ('engine_power', models.CharField(blank=True, max_length=100, verbose_name='Потужність двигуна (л.с.)')),
                ('image', models.URLField(verbose_name='Основне зображення')),
                ('images', models.TextField(blank=True, help_text='URLs зображень, розділені комами', verbose_name='Додаткові зображення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('features', models.TextField(blank=True, verbose_name='Особливості та переваги')),
                ('documents', models.CharField(blank=True, max_length=255, verbose_name='Наявні документи')),
                ('seller_name', models.CharField(max_length=255, verbose_name="Ім'я продавця")),
                ('seller_phone', models.CharField(max_length=20, verbose_name='Телефон продавця')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Email продавця')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combiners', to='products.brand', verbose_name='Марка')),
                ('combiner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combiners', to='products.combinertype', verbose_name='Тип комбайна')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.combinercondition', verbose_name='Стан')),
            ],
            options={
                'verbose_name': 'Комбайн',
                'verbose_name_plural': 'Комбайни',
                'ordering': ['-created_at'],
            },
        ),
    ]
