# Generated by Django 6.0.2 on 2026-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='combiner',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"),
        ),
        migrations.AddField(
            model_name='combinertype',
            name='slug',
            field=models.SlugField(default='exit', max_length=255, unique=True, verbose_name="URL-ім'я"),
            preserve_default=False,
        ),
    ]
