# Generated by Django 6.0.2 on 2026-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_slug_combiner_slug_combinertype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combiner',
            name='image',
            field=models.ImageField(blank=True, upload_to='combiners/', verbose_name='Основне зображення'),
        ),
        migrations.AlterField(
            model_name='combiner',
            name='images',
            field=models.TextField(blank=True, help_text='URLs або шляхи зображень, розділені комами', verbose_name='Додаткові зображення'),
        ),
    ]
