# Generated by Django 6.0.2 on 2026-02-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_combiner_image_alter_combiner_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayerCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excellent', 'Відмінний стан'), ('good', 'Хороший стан'), ('normal', 'Задовільний'), ('poor', 'Потребує ремонту')], max_length=50, unique=True, verbose_name='Стан')),
            ],
            options={
                'verbose_name': 'Стан обприскувача',
                'verbose_name_plural': 'Стани обприскувачів',
            },
        ),
        migrations.CreateModel(
            name='SprayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип обприскувача')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="URL-ім'я")),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип обприскувача',
                'verbose_name_plural': 'Типи обприскувачів',
            },
        ),
        migrations.CreateModel(
            name='TractorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excellent', 'Відмінний стан'), ('good', 'Хороший стан'), ('normal', 'Задовільний'), ('poor', 'Потребує ремонту')], max_length=50, unique=True, verbose_name='Стан')),
            ],
            options={
                'verbose_name': 'Стан трактора',
                'verbose_name_plural': 'Стани тракторів',
            },
        ),
        migrations.CreateModel(
            name='TractorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип трактора')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name="URL-ім'я")),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип трактора',
                'verbose_name_plural': 'Типи тракторів',
            },
        ),
        migrations.CreateModel(
            name='Sprayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель обприскувача')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL-ім'я")),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('working_hours', models.PositiveIntegerField(verbose_name='Годин роботи')),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Дизель'), ('gasoline', 'Бензин'), ('electric', 'Електричний'), ('battery', 'Акумулятор')], max_length=20, verbose_name='Тип палива')),
                ('tank_volume', models.PositiveIntegerField(verbose_name="Об'єм бака (літри)")),
                ('spray_width', models.CharField(blank=True, max_length=100, verbose_name='Ширина розпилювання (м)')),
                ('image', models.ImageField(blank=True, upload_to='sprayers/', verbose_name='Основне зображення')),
                ('images', models.TextField(blank=True, help_text='URLs або шляхи зображень, розділені комами', verbose_name='Додаткові зображення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('features', models.TextField(blank=True, verbose_name='Особливості та переваги')),
                ('documents', models.CharField(blank=True, max_length=255, verbose_name='Наявні документи')),
                ('seller_name', models.CharField(max_length=255, verbose_name="Ім'я продавця")),
                ('seller_phone', models.CharField(max_length=20, verbose_name='Телефон продавця')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Email продавця')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprayers', to='products.brand', verbose_name='Марка')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sprayercondition', verbose_name='Стан')),
                ('sprayer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprayers', to='products.sprayertype', verbose_name='Тип обприскувача')),
            ],
            options={
                'verbose_name': 'Обприскувач',
                'verbose_name_plural': 'Обприскувачі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель трактора')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL-ім'я")),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('working_hours', models.PositiveIntegerField(verbose_name='Годин роботи')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Дизель'), ('gasoline', 'Бензин'), ('gas', 'Газ')], max_length=20, verbose_name='Тип палива')),
                ('engine_power', models.CharField(blank=True, max_length=100, verbose_name='Потужність двигуна (л.с.)')),
                ('image', models.ImageField(blank=True, upload_to='tractors/', verbose_name='Основне зображення')),
                ('images', models.TextField(blank=True, help_text='URLs або шляхи зображень, розділені комами', verbose_name='Додаткові зображення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('features', models.TextField(blank=True, verbose_name='Особливості та переваги')),
                ('documents', models.CharField(blank=True, max_length=255, verbose_name='Наявні документи')),
                ('seller_name', models.CharField(max_length=255, verbose_name="Ім'я продавця")),
                ('seller_phone', models.CharField(max_length=20, verbose_name='Телефон продавця')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Email продавця')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='products.brand', verbose_name='Марка')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tractorcondition', verbose_name='Стан')),
                ('tractor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='products.tractortype', verbose_name='Тип трактора')),
            ],
            options={
                'verbose_name': 'Трактор',
                'verbose_name_plural': 'Трактори',
                'ordering': ['-created_at'],
            },
        ),
    ]
