# Generated by Django 6.0.2 on 2026-03-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sprayercondition_sprayertype_tractorcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='combiners/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('combiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='products.combiner')),
            ],
            options={
                'verbose_name': 'Додаткове фото',
                'verbose_name_plural': 'Додаткові фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SprayerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sprayers/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('sprayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='products.sprayer')),
            ],
            options={
                'verbose_name': 'Додаткове фото',
                'verbose_name_plural': 'Додаткові фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TractorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tractors/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='products.tractor')),
            ],
            options={
                'verbose_name': 'Додаткове фото',
                'verbose_name_plural': 'Додаткові фото',
                'ordering': ['order'],
            },
        ),
    ]
