# Generated by Django 6.0.2 on 2026-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_combinerimage_sprayerimage_tractorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='combiner',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='sprayer',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='tractor',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місцезнаходження'),
        ),
    ]
